[workspace]
default-members = ["quoridor-cli", "quoridor-game"]
members = [
    "quoridor-cli",
    "quoridor-game",
    "quoridor-wasm",
    "quoridor-python",
    "test_runner"
]

[profile.release]
debug = 1
